minor changes

diff --git a/prtgithub b/prtgithub
--- a/prtgithub
+++ b/prtgithub
@@ -2,16 +2,17 @@
 #
 # list ports that aren't sourced from github
 
-shopt -s globstar
-
-for file in **; {
-    [[ -f $file && $file =~ Pkgfile$ ]] && {
-        . "$file"
+for pkg in *; {
+    [[ -d $pkg ]] && {
+        . "$pkg/Pkgfile" || {
+            echo "${0##*/} : can't source the Pkgfile for '$pkg'" >&2
+            exit 1
+        }
 
         for source in "${source[@]}"; {
             [[ $source =~ github\.com ]] && continue 2
         }
 
-        echo "${file%%/*}"
+        echo "$pkg"
     }
 }
